### PR TITLE
Draw a hidden field on the form so that we can use it in processing

### PR DESCRIPTION
**Pull request by jemaleddin**
On a project we're relying on this to fill in Admin Titles based on separate campuses, but if nothing ends up getting drawn, then nothing ends up in the data array.

### CODE REVIEW

**Comment by timbuckingham** [comment]
The issue I see with this is that the user could technically edit the value if it stored in the form. Maybe we give an option to draw it in the form or not.

**Comment by jemaleddin** [comment]
Is there something else we can do to have hidden values available to processing hooks?

**Comment by timbuckingham** [comment]
I think the publish hook should have the data. So would the post processing hook. Is it needed in preprocessing?

**Comment by jemaleddin** [comment]
I'm unsure what the differences in contexts are! I can say that we need to
examine a hidden value for, say, a campus, in order to set an admin title of
"campus - title". Can that be done in a different
hook?

**Pull request closed without merging**
